### ISSUE TITLE
Article of the day crashes my web

### ISSUE THREAD

**Issue by imyourguru** [Spudley/mod_articleoftheday#1]
Hi
Im trying to use the article of the day, however it simply refuses to work - when I try and use it, the entire web page just displays nothing.
I am using Yootheme as my template.

Can you help me resolve this please?

thanks

David

**Comment by Spudley** [comment]
Hi.

Thanks for posting the ticket.

If possible, could you provide the PHP error message that is generated?

You can get this by going to the admin panel / global config / server, setting the "Error reporting" flag to the maximum level, and then going back to the page with the error. This should then give you an error message instead of the white screen, which you can copy+paste here. Make sure to turn the setting back off again afterwards.

Please also provide further details of your system - for example, the Joomla version, PHP version, and any other extensions you may be using.

Please note, I have not tested this extension with Yootheme.

**Comment by pepperstreet** [comment]
Late to the party, but I had a weird site crash too. Hard to investigate, because I was not able to log or display a detailed error. Eventually, it seem to be a simple syntax error in the module's main .php file. 
I have created a PR #2

**Comment by Spudley** [comment]
Thanks for the fix.

Strangely, the copy I have on my local machine (and on the site I wrote the plugin for) doesn't have this error, so I don't know how it crept in. But thank you for fixing it. I've merged your change into the master branch.
